### ISSUE TITLE
API - Partial data requests by date

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#1]
Applications should be able to pass the time of their last API request, and receive only information that has changed since that time

**Comment by aosdict** [comment]
May want to push this one aside for now or relegate it to wishlist status, since we have removed the timestamp columns from all tables.

**Comment by aosdict** [comment]
We have built the API in such a way that partial data requests don't really make sense anymore. I recommend closing this issue as "not going to do it".

**Comment by Bad-Science** [comment]
The context of this issue is to take some load off the the server/network in the presence of front end caching. But right now we don't have plans for front end caching at all right now so I agree it should be closed.
