### ISSUE TITLE
Search - order results by number of terms matched

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#14]
When the search API is used to find courses, it should keep track of how many terms in the search query matched a given course. Then when it returns the courses to the user, it should sort the list of courses by that number. All matching results will be displayed, but in order of relevance. This combines the benefits of OR-based searches (show anything that matched) with the benefits of AND-based searches (multiple search terms give the best, most specific result).

Example: Searching for "CourseName ProfName" will return first courses named CourseName which are taught by ProfName, then any other courses named or matching CourseName, then all other courses taught by ProfName.

**Comment by Bad-Science** [comment]
Upgrading this to important. Search is a core function of the app and we need this working ASAP. I'm going to try to work on this tomorrow, but I am concerned about performance. We'll ultimately have to minimize the number of queries made

**Comment by Bad-Science** [comment]
Columns (of courses table) to be evaluated:
- name
- number
- instructors (in array)

Initial implementation will be limited to these three columns. Shortly after this should be expanded to the name and code columns of the departments table.

**Comment by Bad-Science** [comment]
Almost done with this. Found a great resource: http://rachbelaid.com/postgres-full-text-search-is-good-enough/

Postgres has some great features built in for lighter searching. Following the approach in this article, i've implemented a pure SQL search function capable of searching across as many columns as we want. Progress currently in "search" branch. Will make a PR soon.
