### ISSUE TITLE
Asynchronous AJAX calls

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#18]
Ajax calls (namely getting course xml data from api) are synchronous, and cause the browser window to freeze during long response times. frontend caching would mitigate this issue as well, but the calls should really be asynchronous.

**Comment by aosdict** [comment]
Not sure how this can be made asynchronous and still work reliably. For example, a click event has to be placed on every section element, without which clicking on the section does nothing. If the click event handling code is completed before some or all of the section elements load, those elements won't get the event handlers.

**Comment by Bad-Science** [comment]
The solution seems to be not to update the page at all until the network request has completed. Thoughts?

**Comment by Bad-Science** [comment]
edit: after looking through the js code again everything should be handles with callbacks. i'm attempting to do this now

**Comment by Bad-Science** [comment]
fixed by https://github.com/aosdict/yacs/commit/daa8be65f7b8c8a3f70d4898ec437eed46dad398

Now a some sort of "loading" message is needed so you can tell it is working... created https://github.com/aosdict/yacs/issues/24
