### ISSUE TITLE
Display section period information

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#20]
In the courses view, period information should be displayed alongside each section. Each section should show the day, time, and type of each period. Please comment with how this data should preferably exposed by the xml api.

**Comment by Bad-Science** [comment]
backend done: 0b87fae85aede7d4036219be95e160b41aef2d71

**Comment by aosdict** [comment]
Needs a few tweaks (sorting primarily)

**Comment by aosdict** [comment]
Pretty much finished; it can always be tweaked later and there's still a lack of course sorting but that's an API issue.
