### ISSUE TITLE
Loading catalog should update previously populated database

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#22]
Currently, the database cam only be populated from empty in one shot. loading the catalog should update existing entries and add new ones where appropriate.

**Comment by aosdict** [comment]
You think this is more of a General Release thing? I can't imagine that the single RPI instance will need to reload the database too often.

**Comment by Bad-Science** [comment]
I've been watching the data over the past few days and even this late sections are being added. in light of this, I've added a catalog update procedure that can add (but not remove) courses and sections that did not previously exist. This system will need to be revisited and improved for #30 but for now I am adding this back to RPI release and closing
