### ISSUE TITLE
Automated seat count updating (database level)

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#23]
A key part of the application's function is automatic and timely updates to seat count information. The information will be parsed from the xml file found here https://sis.rpi.edu/reg/rocs/YACS_201601.xml

A suggested approach is to poll this file every minute or so and store it in memory. On each subsequent poll, diff the new file with the one previously stored, and update sections corresponding to changed lines. (obviously) then update the locally stored copy. The records corresponding to the changes seat counts should then be updated in the database.

**Comment by aosdict** [comment]
It's unclear whether you want this to be done on the backend, frontend, or both.

**Comment by Bad-Science** [comment]
My understand was that only the schools/departments/subjects files will be tab or comma delimited. Maybe I am mis-remembering.

**Comment by Bad-Science** [comment]
But to answer the first question, this issue was for the backend (updating the records in the database). Should have been more clear will edit the issue. Updating the seats information on the front end automatically without reloading the page should also be done, but this is less vital and may not be needed for the first milestone. I will create a separate issue for this.

**Comment by Bad-Science** [comment]
e180daf resolves the initial issue but is unoptimized. closing this and created #46
