### ISSUE TITLE
Loading message needed when loading course xml from api

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#24]
Could be a message, wheel, bar, whatever you want get creative.

**Comment by Bad-Science** [comment]
cool idea: some sort of oscillating fade effect with the YACS link in the top left or the department name.
I like the former better, the YACS text could serve as a universal loading bar for the application.

**Comment by aosdict** [comment]
Design may change, but I've put in a classic "loading dots" gif that appears in the main content area in the absence of any other content. I personally don't like the idea of using the YACS text to indicate loading; it's the main page title and is all the way in the corner of the screen.
