### ISSUE TITLE
Course titles and descriptions pulled from course catalog are badly formatted

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#32]
As the issue title says. There are known problems with capitalization in the course titles - looking through ITWS courses gets me results like "Introduction To Hci" and "It and Society". 

In addition, course descriptions contain a repeat of the course department, number, and title smushed up against the actual description text, like "ITWS 2210 - Introduction to Human Computer InteractionAn introduction to the current theories, methods, and issues in human-computer interaction..."

This is a problem with the course catalog parser (the erroneous text is represented that way in the database).

**Comment by Bad-Science** [comment]
This will presumably be fixed by https://github.com/aosdict/yacs/issues/30

**Comment by Bad-Science** [comment]
partially fixed with https://github.com/aosdict/yacs/commit/66306d2ebb62395b8beec3cd86c7c1d911b3d9ac (course names but not descriptions)

**Comment by Bad-Science** [comment]
closed with fed898a and  66306d2
