### ISSUE TITLE
Representation of closed courses in the course list and on the schedule

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#44]
There is nothing stopping students from selecting closed sections, as per our design. Therefore, there needs to be some noticeable way of representing closed sections. 

We haven't discussed the appearance of closed courses on the course list (my initial idea is coloring the "0 seats" text YACS red.) For closed courses on the schedule, we decided that a diagonally striped background, perhaps in the same color as that course's background would be, would work.

**Comment by Bad-Science** [comment]
I think the striped background would be good for sections too

**Comment by aosdict** [comment]
Striped translucent gray background for periods on the schedule (that overlays its normal background color). We decided that using it on sections would be too noisy so we are just using gray text for it.
