### ISSUE TITLE
Text between schedule selection arrows does not change when arrows are pressed

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#48]
Pressing the selection arrows should update the text "1/N" to "2/n" ... 

Also, the text and should not be selectable. currently, clicking them a few times results in them being highlighted.

**Comment by aosdict** [comment]
Removing frontend label until we confirm this is a frontend problem; I think it's just the default behavior of the schedule API. Currently if I select two sections of the same class with the same time, I'll get two schedules that look identical but in fact display different section numbers.

If the API is causing this, we probably need to discuss what to do to avoid this misleading presentation. May want to mark this up as a future issue to consolidate such identical schedules and untag it as a bug.

With regards to the selectability, I just patched that.

**Comment by Bad-Science** [comment]
This issue in only in reference to the text "Schedule 1/N" above the schedule not the schedule display itself. Changing schedule works but it should say "Schedule 1/N"..."Schedule N/N" as you click through them.

**Comment by aosdict** [comment]
Sorry, that is correct. I have just patched this.
