### ISSUE TITLE
Add arrow key navigation to schedule page

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#49]
When on the schedule page, the user should be able to hit Left and Right on the arrow keys to navigate between schedules. This may require revising the auto-searchbar-focus functionality slightly.

**Comment by Bad-Science** [comment]
I though of this today as well. Can be implemented with only a slight modification to searchbar focus functionality (ie just dont focus the search bar if they key pressed is an arrow key)

**Comment by aosdict** [comment]
Implementation was more complex than expected. In order to process the key events correctly, there needs to be a global key handler whose event listener is added once when the DOM initially loads. A side effect of resolving this was that now there are new variables and constants to track which page the user is currently on. Up/Down were also added with the same functionality as Left/Right.

In any case, this is done.
