### ISSUE TITLE
Exclude courses with no periods from scheduler

### ISSUE THREAD

**Issue by Bad-Science** [aosdict/yacs#59]
The scheduler does not currently ignore courses without periods, resulting is many, many schedules if you were to select, for example, a Master's Thesis. Perhaps we should not even display sections with no periods, or maybe display them but now allow them to be selected. Thoughts @aosdict ?

**Comment by aosdict** [comment]
Ideally they'd be selectable on the course list, and viewable and deselectable in the list of courses on the schedule page, but without affecting the actual schedules object. This is related to #40; we haven't designed how at list of selected courses would be populated yet.

**Comment by aosdict** [comment]
Yeah, so the way things are going, it looks like the best thing to do is just have the scheduler ignore these sections entirely. That way, people can still select them and deselect them on the schedule page, they won't appear on the schedule but they'll still be in the cookie as selected sections, meaning they'll be eligible to get copied for CRNs or whatever.

The only actual problem with it as it stands is that they multiply schedules, so removing that behavior is the way to go.

**Comment by Bad-Science** [comment]
closed with 8d1e2fd
