### ISSUE TITLE
Fancy search

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#6]
Ideally, the search bar should be able to process basic sentence structure, such as: "math class taught by Professor Rainsford at 10 AM on Monday and Thursday", which would then break down into the search components (department = math && professor = Rainsford && start-time = 10AM && (day = Monday || day = Thursday).

**Comment by aosdict** [comment]
I doubt anyone is actually going to make searches like the above example, so we probably aren't going to make a grammar-parsing search. However, we still want a "fancy" intelligent search.

**Comment by aosdict** [comment]
This might be able to be closed as "good enough" with the new full-text search.

**Comment by Bad-Science** [comment]
@aosdict agreed, this can be closed. potential for search enhancements can be re-evaluated in the future, but this idea may conflict with the current implementation and the current implementation is "good enough" even without enhancement
