### ISSUE TITLE
Schedule display days are off by one

### ISSUE THREAD

**Issue by bennyty** [aosdict/yacs#60]
Someone thought weeks started on a Monday and someone thought they started on a Sunday. ![](http://puu.sh/n8lWN/09564e6e90.png) This class is on Mondays and Thursdays, same for all other classes.

**Comment by aosdict** [comment]
Yeah, this was issue #37. I'm pretty sure this is just because the Heroku database didn't get updated or something. When I select this course using my own database, the days that show up are Monday-Thursday. I let Richie know about this.

**Comment by bennyty** [comment]
Sounds good. I just figured #37 was closed but somehow it made it to live.

**Comment by aosdict** [comment]
Yup, this was just Heroku not being updated. Richie just fixed that.
