### ISSUE TITLE
Split up Javascript and CSS source files

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#62]
We have one Javascript file only, yacs-main.js, and it's getting really long and I am having a hard time navigating through it and finding where code is. It should really be broken up logically into several different files. Constants, variables, general helper functions, home page code, course page code, and schedule code are some divisions I can think of right now.

We should look into how we can make the server merge and minify all the Javascript into one file so the Web app will still only treat it as that one file. Once we have a way to do that, we can split the code into multiple files.

Also tagging this as performance since minified JS is a speed improvement.

**Comment by aosdict** [comment]
The files are all split up; however, I don't think they are being minified yet, and I think they aren't being merged either.

**Comment by aosdict** [comment]
Also, this should be done to CSS files, since it's also pretty logically broken up into different page styles.

**Comment by Bad-Science** [comment]
@aosdict the files are only minified and combined in production. can confirm this works.
