### ISSUE TITLE
Make clicking on a course deselect all its sections when all sections are either selected or closed

### ISSUE THREAD

**Issue by aosdict** [aosdict/yacs#69]
Currently, clicking on a course will only deselect every section in the course when all sections are selected. Since courses are likely to have one or two closed sections that won't be selected by the initial click on the course, the behavior should be changed so that it ignores closed sections when checking to see if all the sections are selected.

**Comment by Bad-Science** [comment]
I noticed this as well thanks

**Comment by aosdict** [comment]
This is implemented as of 2608408.
